/*
|-----------------------------------------
| setting up demoProductsData.ts for the App
| @author: Toufiquer Rahman<toufiquer.0@gmail.com>
| @copyright: Toufiquer, 01 September, 2026
|-----------------------------------------
*/

import { emptyRichText, normalizeSlug, type ProductInput } from "./catalog";

export type RawDemoProduct = {
  name: string;
  brand: string;
  realPrice: number;
  discountPrice: number;
  stock: number;
  star: number;
  shortDescription: string;
  features: string[];
  image: string;
};

// 50 unique demo products with unique names, unique prices, and realistic specs
export const DEMO_PRODUCTS: RawDemoProduct[] = [
  {
    name: "SonicPulse Wireless Noise-Cancelling Headphones",
    brand: "SonicPulse",
    realPrice: 4500,
    discountPrice: 3825,
    stock: 28,
    star: 4.8,
    shortDescription: "Premium over-ear headphones with 40dB active noise cancellation and 45h battery life.",
    features: ["Active Noise Cancellation 40dB", "45-hour playback time", "Fast USB-C charging", "Multipoint Bluetooth 5.3"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "KeyForge Pro RGB Mechanical Keyboard",
    brand: "KeyForge",
    realPrice: 5200,
    discountPrice: 4420,
    stock: 19,
    star: 4.7,
    shortDescription: "Hot-swappable mechanical keyboard with custom switches and per-key RGB backlighting.",
    features: ["Hot-swappable switches", "Double-shot PBT keycaps", "Per-key RGB customization", "Aircraft-grade aluminum frame"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AeroGlide Ergonomic Wireless Mouse",
    brand: "AeroGlide",
    realPrice: 1850,
    discountPrice: 1572.5,
    stock: 35,
    star: 4.6,
    shortDescription: "Precision optical mouse with 4000 DPI sensor, silent clicks, and dual-mode wireless connectivity.",
    features: ["Dual Bluetooth & 2.4GHz USB", "Adjustable DPI up to 4000", "Silent micro-switches", "Rechargeable 600mAh battery"],
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "UltraView 34-inch Curved Gaming Monitor",
    brand: "UltraView",
    realPrice: 38900,
    discountPrice: 33065,
    stock: 12,
    star: 4.9,
    shortDescription: "Ultrawide 1500R curved monitor with 165Hz refresh rate and 1ms response time.",
    features: ["WQHD 3440x1440 resolution", "165Hz high refresh rate", "HDR400 certified", "1500R immersive curvature"],
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "HyperCharge 100W GaN Fast Charger",
    brand: "HyperCharge",
    realPrice: 2450,
    discountPrice: 2082.5,
    stock: 45,
    star: 4.8,
    shortDescription: "Compact 4-port GaN charger capable of powering laptops, tablets, and smartphones simultaneously.",
    features: ["100W Power Delivery 3.0", "3x USB-C + 1x USB-A ports", "Advanced GaN III technology", "Comprehensive surge protection"],
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "NovaBeam 4K Ultra HD Streaming Webcam",
    brand: "NovaBeam",
    realPrice: 6800,
    discountPrice: 5780,
    stock: 22,
    star: 4.5,
    shortDescription: "Ultra HD webcam with autofocus, dual noise-reducing microphones, and privacy shutter.",
    features: ["4K UHD at 30fps / 1080p at 60fps", "Built-in dual stereo microphones", "Physical privacy shutter", "Plug and play USB-C"],
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "PulseFit Smart Fitness Tracker Watch",
    brand: "PulseFit",
    realPrice: 3200,
    discountPrice: 2720,
    stock: 40,
    star: 4.4,
    shortDescription: "Waterproof smartwatch featuring 24/7 heart rate monitoring, SpO2 sensor, and 14-day battery life.",
    features: ["1.47-inch AMOLED display", "24/7 Heart rate & SpO2 tracking", "5ATM water resistance", "14 days standby battery"],
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SoundWave Portable Bluetooth Speaker",
    brand: "SoundWave",
    realPrice: 2750,
    discountPrice: 2337.5,
    stock: 31,
    star: 4.7,
    shortDescription: "Rugged waterproof outdoor speaker with punchy bass, 20W dual drivers, and IPX7 rating.",
    features: ["20W stereo output with deep bass", "IPX7 waterproof rating", "16-hour playtime", "TWS dual speaker pairing"],
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "FlexiStand Aluminum Laptop Riser",
    brand: "FlexiStand",
    realPrice: 1450,
    discountPrice: 1232.5,
    stock: 50,
    star: 4.6,
    shortDescription: "Ergonomic foldable laptop stand with heat dissipation vents and non-slip silicone padding.",
    features: ["Adjustable height & viewing angles", "CNC-machined aluminum alloy", "Foldable & portable design", "Supports up to 17-inch laptops"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "StreamCast Studio USB Microphone",
    brand: "StreamCast",
    realPrice: 4850,
    discountPrice: 4122.5,
    stock: 18,
    star: 4.7,
    shortDescription: "Cardioid condenser microphone with tap-to-mute sensor, gain dial, and headphone monitor jack.",
    features: ["Studio-grade cardioid pickup", "Touch-sensitive tap-to-mute", "Zero-latency 3.5mm monitoring", "Built-in pop filter and shock mount"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "PowerVault 20000mAh Fast Charging Bank",
    brand: "PowerVault",
    realPrice: 2950,
    discountPrice: 2507.5,
    stock: 33,
    star: 4.8,
    shortDescription: "High-capacity power bank featuring 22.5W bidirectional quick charging and digital LED display.",
    features: ["20000mAh battery capacity", "22.5W Fast Charge & PD 20W", "Smart digital battery percentage", "Triple output ports"],
    image: "https://images.unsplash.com/photo-1609592424361-9c6a7e0c9c74?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "OmniHub 9-in-1 USB-C Multiport Adapter",
    brand: "OmniHub",
    realPrice: 3400,
    discountPrice: 2890,
    stock: 25,
    star: 4.6,
    shortDescription: "Universal USB-C hub with 4K HDMI, Gigabit Ethernet, SD card reader, and 100W PD passthrough.",
    features: ["4K@60Hz HDMI video output", "1000Mbps Gigabit RJ45", "100W Power Delivery port", "SD & TF card reader slots"],
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "VividDesk RGB Gaming Extended Mousepad",
    brand: "VividDesk",
    realPrice: 1250,
    discountPrice: 1062.5,
    stock: 42,
    star: 4.5,
    shortDescription: "Large 800x300mm desk mat with micro-textured cloth surface and 14 RGB lighting modes.",
    features: ["800x300mm extended surface", "14 dynamic RGB lighting modes", "Water-resistant coating", "Anti-skid rubber base"],
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "LuminaTouch Smart LED Desk Lamp",
    brand: "LuminaTouch",
    realPrice: 2350,
    discountPrice: 1997.5,
    stock: 29,
    star: 4.7,
    shortDescription: "Eye-care desk lamp with 5 color temperatures, step-less touch dimming, and USB charging port.",
    features: ["Flicker-free eye protection", "5 color modes & brightness slider", "Integrated 5V/1A USB port", "Auto-off 45min timer"],
    image: "https://images.unsplash.com/photo-1534447677768-be436bb09401?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AirBeat True Wireless Earbuds ANC",
    brand: "AirBeat",
    realPrice: 3650,
    discountPrice: 3102.5,
    stock: 36,
    star: 4.6,
    shortDescription: "Sleek in-ear wireless earbuds with active noise cancellation, transparency mode, and low latency.",
    features: ["Active Noise Cancellation & Ambient Mode", "32-hour battery with wireless case", "Dual mic ENC call clarity", "IPX5 sweat resistance"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "DataShield 1TB Portable External SSD",
    brand: "DataShield",
    realPrice: 9500,
    discountPrice: 8075,
    stock: 15,
    star: 4.9,
    shortDescription: "Ultra-fast NVMe portable drive with up to 1050MB/s transfer speed and drop-resistant casing.",
    features: ["1050MB/s read/write speed", "USB 3.2 Gen 2 Type-C", "Shock & vibration resistant", "Hardware AES 256-bit encryption"],
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "MagGrip Magnetic Car Phone Mount",
    brand: "MagGrip",
    realPrice: 950,
    discountPrice: 807.5,
    stock: 55,
    star: 4.4,
    shortDescription: "Secure air vent car mount with 16 strong neodymium magnets and 360-degree ball joint.",
    features: ["Strong N52 magnetic array", "360-degree rotation ball joint", "Universal air vent clip", "One-hand snap and go"],
    image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "ErgoSpine Mesh High-Back Office Chair",
    brand: "ErgoSpine",
    realPrice: 16500,
    discountPrice: 14025,
    stock: 8,
    star: 4.8,
    shortDescription: "Ergonomic mesh chair with adaptive lumbar support, 3D armrests, and breathable mesh fabric.",
    features: ["Adaptive dynamic lumbar support", "3D adjustable armrests", "135-degree recline with lock", "Breathable Korean mesh fabric"],
    image: "https://images.unsplash.com/photo-1580481077195-c3a82105e3b5?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "NetSpeed Wi-Fi 6 Gigabit Router",
    brand: "NetSpeed",
    realPrice: 5800,
    discountPrice: 4930,
    stock: 20,
    star: 4.7,
    shortDescription: "Dual-band AX3000 router with OFDMA, MU-MIMO, beamforming, and 4 high-gain antennas.",
    features: ["AX3000 speeds up to 3Gbps", "4 external high-gain antennas", "Connects up to 128 devices", "WPA3 next-gen security"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "StudioLink Dual Monitor Desk Arm",
    brand: "StudioLink",
    realPrice: 4200,
    discountPrice: 3570,
    stock: 14,
    star: 4.6,
    shortDescription: "Gas-spring dual monitor mount supporting two screens up to 32-inch with integrated cable guides.",
    features: ["Supports dual 17-32 inch screens", "Smooth gas-spring articulation", "75x75 and 100x100 VESA compatible", "Integrated cable management"],
    image: "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "PureMist Ultrasonic Air Humidifier",
    brand: "PureMist",
    realPrice: 2150,
    discountPrice: 1827.5,
    stock: 26,
    star: 4.5,
    shortDescription: "Whisper-quiet 3L cool mist humidifier with ambient LED nightlight and essential oil tray.",
    features: ["3L large water tank", "Whisper-quiet operation (<28dB)", "Aroma diffuser oil tray", "Auto shut-off when dry"],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "PixelSharp 2K Smart Home Security Cam",
    brand: "PixelSharp",
    realPrice: 3100,
    discountPrice: 2635,
    stock: 38,
    star: 4.7,
    shortDescription: "360-degree pan-tilt indoor Wi-Fi camera with 2K resolution, infrared night vision, and motion tracking.",
    features: ["2K 3MP crystal-clear video", "360-degree panoramic coverage", "AI human detection & tracking", "Two-way audio communication"],
    image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "VoltSafe Smart Wi-Fi Power Strip",
    brand: "VoltSafe",
    realPrice: 2200,
    discountPrice: 1870,
    stock: 30,
    star: 4.6,
    shortDescription: "Surge-protected 4-outlet smart strip with 4 USB charging ports, voice control, and app scheduling.",
    features: ["4 independently controllable AC outlets", "4 fast-charging USB ports", "Compatible with Alexa & Google Home", "1700J surge protection"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "GamerArmor Hard-Shell Laptop Backpack",
    brand: "GamerArmor",
    realPrice: 3750,
    discountPrice: 3187.5,
    stock: 24,
    star: 4.8,
    shortDescription: "Water-resistant EVA hard-shell backpack designed for 17.3-inch gaming laptops and accessories.",
    features: ["Shockproof EVA front shell", "Fits up to 17.3-inch laptops", "Hidden anti-theft back pocket", "External USB charging port"],
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "ChronoGlow Retro Nixie Tube Desk Clock",
    brand: "ChronoGlow",
    realPrice: 6200,
    discountPrice: 5270,
    stock: 10,
    star: 4.9,
    shortDescription: "Modern vintage IPS digital clock mimicking classic glowing nixie tubes with custom dial faces.",
    features: ["6 customizable IPS screen tubes", "RGB mood ambient bottom lights", "Precision quartz time keeping", "USB-C power connection"],
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SwiftGlide PBT Keycaps Custom Set",
    brand: "SwiftGlide",
    realPrice: 1650,
    discountPrice: 1402.5,
    stock: 40,
    star: 4.7,
    shortDescription: "Cherry profile 136-key dye-sub PBT keycap set compatible with standard MX stem switches.",
    features: ["136 keycaps for multiple layouts", "Durable dye-sublimation legends", "Thick 1.5mm PBT plastic", "Universal cross-stem fit"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AuraCast 10-inch LED Ring Light",
    brand: "AuraCast",
    realPrice: 1750,
    discountPrice: 1487.5,
    stock: 35,
    star: 4.5,
    shortDescription: "Dimmable makeup and video streaming ring light with adjustable 50-inch tripod and phone holder.",
    features: ["3 lighting modes & 10 brightness levels", "Extendable aluminum tripod stand", "Flexible 360-degree phone clamp", "Bluetooth remote shutter included"],
    image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "ThermaMug Smart Temperature Heated Mug",
    brand: "ThermaMug",
    realPrice: 4250,
    discountPrice: 3612.5,
    stock: 16,
    star: 4.7,
    shortDescription: "App-controlled ceramic mug with built-in heater keeping coffee or tea perfectly hot for up to 3 hours.",
    features: ["Maintains drink at 120°F - 145°F", "App control with temperature presets", "Coaster charging plate included", "Auto sleep sensor detection"],
    image: "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AirDuster Turbo Electric Cordless Blower",
    brand: "AirDuster",
    realPrice: 2600,
    discountPrice: 2210,
    stock: 27,
    star: 4.6,
    shortDescription: "Powerful 90000RPM brushless motor electric blower for deep cleaning PC electronics and keyboards.",
    features: ["90000 RPM high-speed motor", "3 adjustable air flow gears", "Type-C rechargeable 7500mAh battery", "Includes 5 cleaning nozzle attachments"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "DeskZen Bamboo Desktop Cable Organizer",
    brand: "DeskZen",
    realPrice: 850,
    discountPrice: 722.5,
    stock: 60,
    star: 4.5,
    shortDescription: "Natural bamboo storage box designed to conceal messy power strips, surge protectors, and cords.",
    features: ["Eco-friendly natural bamboo", "Ventilated heat dissipation slots", "Fits standard 6-outlet strips", "Non-scratch rubber feet"],
    image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "OptiGuard Blue Light Blocking Glasses",
    brand: "OptiGuard",
    realPrice: 1100,
    discountPrice: 935,
    stock: 48,
    star: 4.6,
    shortDescription: "Lightweight TR90 frames filtering 99% of harmful digital blue rays to reduce digital eye strain.",
    features: ["UV400 & blue ray filtering", "Ultra-lightweight TR90 frame", "Anti-reflective clear lenses", "Durable spring-loaded hinges"],
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SoundPod Studio Reference Monitor Speakers",
    brand: "SoundPod",
    realPrice: 11800,
    discountPrice: 10030,
    stock: 9,
    star: 4.8,
    shortDescription: "Pair of active near-field studio monitors featuring 5-inch Kevlar woofers and silk dome tweeters.",
    features: ["5-inch woven Kevlar low-frequency drivers", "1-inch natural silk dome tweeters", "Bi-amplified Class A/B 80W power", "Balanced XLR and 1/4-inch inputs"],
    image: "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "FlexiArm Heavy Duty Mic Boom Stand",
    brand: "FlexiArm",
    realPrice: 2100,
    discountPrice: 1785,
    stock: 32,
    star: 4.7,
    shortDescription: "Smooth articulated scissor arm stand with internal springs and hidden cable management channels.",
    features: ["Full 360-degree rotation", "Holds microphones up to 2kg", "Integrated cable groove track", "Heavy-duty desk clamp mount"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "TitanLink Ultra High Speed HDMI 2.1 Cable",
    brand: "TitanLink",
    realPrice: 750,
    discountPrice: 637.5,
    stock: 75,
    star: 4.8,
    shortDescription: "Braided 48Gbps HDMI cable supporting 8K@60Hz and 4K@120Hz with eARC and Dynamic HDR.",
    features: ["48Gbps high bandwidth", "Supports 8K@60Hz and 4K@120Hz", "Double braided nylon sleeve", "24K gold-plated connectors"],
    image: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "ErgoRest Memory Foam Mouse Wrist Support",
    brand: "ErgoRest",
    realPrice: 650,
    discountPrice: 552.5,
    stock: 65,
    star: 4.5,
    shortDescription: "Contoured ergonomic wrist rest made of high-density cooling memory foam with anti-skid base.",
    features: ["Cooling gel infused memory foam", "Ergonomic wrist-hugging contour", "Smooth Lycra fabric surface", "Non-slip PU backing"],
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "MagStation 3-in-1 Foldable Charging Stand",
    brand: "MagStation",
    realPrice: 3850,
    discountPrice: 3272.5,
    stock: 23,
    star: 4.8,
    shortDescription: "Foldable travel magnetic charging station for iPhone, Apple Watch, and AirPods at once.",
    features: ["Fast 15W MagSafe wireless charging", "Foldable travel-friendly design", "Charges phone, watch, and buds together", "Includes 30W adapter and cable"],
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "GripMaster Mechanical Gaming Mousepad",
    brand: "GripMaster",
    realPrice: 990,
    discountPrice: 841.5,
    stock: 52,
    star: 4.6,
    shortDescription: "Speed-oriented woven cloth gaming mousepad with stitched fray-proof edges and textured base.",
    features: ["Low-friction cloth micro-weave", "Stitched anti-fray borders", "4mm cushioned high-density foam", "Machine washable fabric"],
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SmartTag Bluetooth Tracker Finder Pack",
    brand: "SmartTag",
    realPrice: 2400,
    discountPrice: 2040,
    stock: 34,
    star: 4.4,
    shortDescription: "Ultra-thin item locator tags compatible with iOS Find My network with 1-year replaceable battery.",
    features: ["Works with Apple Find My network", "Loud 95dB built-in buzzer", "IP67 water and dust resistant", "CR2032 replaceable coin battery"],
    image: "https://images.unsplash.com/photo-1584438784894-089d6a62b8fa?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SilentStrike 60% Wireless Mechanical Keyboard",
    brand: "SilentStrike",
    realPrice: 4700,
    discountPrice: 3995,
    stock: 17,
    star: 4.7,
    shortDescription: "Ultra-compact 61-key layout keyboard with pre-lubed silent switches and Bluetooth 5.0.",
    features: ["Compact 60% desk-saving layout", "Pre-lubed linear silent switches", "Triple connection (BT / 2.4G / Wire)", "Hot-swappable 5-pin PCB"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "HyperDrive Pro USB 3.2 Dual Flash Drive 256GB",
    brand: "HyperDrive",
    realPrice: 1950,
    discountPrice: 1657.5,
    stock: 44,
    star: 4.7,
    shortDescription: "Swivel metal dual flash drive with both USB Type-A and Type-C connectors with 400MB/s speeds.",
    features: ["Dual USB-C and USB-A connectors", "Up to 400MB/s read transfers", "All-metal zinc alloy casing", "Plug and play OTG support"],
    image: "https://images.unsplash.com/photo-1597872200969-2b65d56bd16b?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AquaGlow RGB Gaming Headset Stand",
    brand: "AquaGlow",
    realPrice: 1350,
    discountPrice: 1147.5,
    stock: 37,
    star: 4.5,
    shortDescription: "Weighted aluminum headphone hanger featuring dynamic RGB lighting and dual USB pass-through ports.",
    features: ["Dynamic RGB base lighting", "2x USB 2.0 pass-through ports", "Weighted non-tip aluminum base", "Soft rubber protective headrest"],
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "VoicePilot Wireless Presentation Clicker",
    brand: "VoicePilot",
    realPrice: 1150,
    discountPrice: 977.5,
    stock: 46,
    star: 4.6,
    shortDescription: "Ergonomic 2.4GHz presenter remote with bright red laser pointer and 100-foot wireless range.",
    features: ["Bright red laser pointer", "Up to 100ft / 30m control distance", "Plug-and-play USB receiver dock", "Intuitive slideshow tactile buttons"],
    image: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SoundPulse ANC Wireless Neckband Earphones",
    brand: "SoundPulse",
    realPrice: 1890,
    discountPrice: 1606.5,
    stock: 39,
    star: 4.4,
    shortDescription: "Flexible silicone neckband with magnetic earbuds, active noise reduction, and 24-hour battery.",
    features: ["Active environmental noise reduction", "24-hour continuous playback", "Magnetic auto pause/play buds", "IPX5 water & splash resistance"],
    image: "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "ChronoView Smart Weather Station Clock",
    brand: "ChronoView",
    realPrice: 2850,
    discountPrice: 2422.5,
    stock: 21,
    star: 4.6,
    shortDescription: "Color LCD digital alarm clock with wireless outdoor sensor displaying temperature and forecast.",
    features: ["Color HD LCD display panel", "Wireless outdoor remote sensor", "Indoor & outdoor humidity monitor", "Atomic time auto-synchronization"],
    image: "https://images.unsplash.com/photo-1508057198894-247b23fe5ade?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "DeskArmor Dual-Sided PU Leather Pad",
    brand: "DeskArmor",
    realPrice: 790,
    discountPrice: 671.5,
    stock: 62,
    star: 4.5,
    shortDescription: "Reversible water-resistant desk blotter with smooth PU leather surface in 900x400mm dimensions.",
    features: ["Dual-sided two-color design", "Waterproof and easy to wipe clean", "900x400mm large workspace area", "Includes matching strap for travel"],
    image: "https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "SafeLens Webcam Privacy Cover Slide (5 Pack)",
    brand: "SafeLens",
    realPrice: 350,
    discountPrice: 297.5,
    stock: 90,
    star: 4.7,
    shortDescription: "Ultra-thin 0.7mm webcam sliders protecting your privacy on laptops, monitors, tablets, and smartphones.",
    features: ["Ultra-thin 0.7mm profile", "Strong 3M adhesive backing", "Smooth finger slide mechanism", "Fits laptops, Macs, and tablets"],
    image: "https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "PowerFlex 100W Magnetic USB-C Fast Cable",
    brand: "PowerFlex",
    realPrice: 890,
    discountPrice: 756.5,
    stock: 58,
    star: 4.6,
    shortDescription: "Detachable magnetic head fast charging cable supporting 100W Power Delivery with LED indicator.",
    features: ["100W USB-PD fast charging", "Strong 9-pin magnetic snap tip", "Reinforced nylon braided wire", "Smart LED power indicator light"],
    image: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AirVent Under-Desk PC Mount Bracket",
    brand: "AirVent",
    realPrice: 2400,
    discountPrice: 2040,
    stock: 19,
    star: 4.7,
    shortDescription: "Heavy-duty steel adjustable under-desk tower holder holding computer chassis up to 25kg off the floor.",
    features: ["Holds PC towers up to 25kg", "Adjustable height and width", "360-degree swivel for cable access", "Prevents carpet dust buildup"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "GigaSpeed Type-C High Speed SD Card Reader",
    brand: "GigaSpeed",
    realPrice: 720,
    discountPrice: 612,
    stock: 68,
    star: 4.5,
    shortDescription: "Compact aluminum UHS-II memory card reader with simultaneous SD and MicroSD read/write support.",
    features: ["UHS-II speeds up to 312MB/s", "Dual SD + TF simultaneous read", "Durable space gray aluminum body", "Universal USB-C compatibility"],
    image: "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80",
  },
  {
    name: "AuraKey Folding Pocket Bluetooth Keyboard",
    brand: "AuraKey",
    realPrice: 2650,
    discountPrice: 2252.5,
    stock: 25,
    star: 4.6,
    shortDescription: "Ultra-slim tri-folding wireless keyboard with built-in touchpad and multi-device connection.",
    features: ["Pocket-sized tri-fold design", "Integrated sensitive touchpad", "Connects up to 3 devices", "Aircraft aluminum alloy casing"],
    image: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
  },
];

/**
 * Builds a valid, ready-to-POST ProductInput payload from a demo product definition.
 */
export function buildDemoProductPayload({
  demo,
  index,
  categoryId,
  imageUrl,
}: {
  demo: RawDemoProduct;
  index: number;
  categoryId: string;
  imageUrl?: string;
}): ProductInput {
  const seed = `${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 6)}-${index + 1}`.toLowerCase();
  const slug = normalizeSlug(`${demo.name}-${seed}`);
  const sku = `DEMO-${seed.toUpperCase()}`;
  const primaryImage = imageUrl || demo.image;

  // Exact discount calculation ensuring discount matches backend check:
  // Math.abs(expectedDiscount - discount) <= 0.01
  const realPrice = demo.realPrice;
  const discountPrice = demo.discountPrice;
  const discount = realPrice > 0 ? Number((((realPrice - discountPrice) / realPrice) * 100).toFixed(2)) : 0;

  return {
    name: demo.name,
    slug,
    description: emptyRichText,
    shortDescription: demo.shortDescription,
    realPrice,
    discountPrice,
    discount,
    star: demo.star,
    primaryImage,
    images: [primaryImage],
    video: "",
    mainFeatures: demo.features,
    deliveryTime: "2–4 business days",
    warranty: "1 Year Official Warranty",
    stock: demo.stock,
    sku,
    categories: [categoryId],
    brand: demo.brand,
    status: "active",
    isFeatured: index < 5,
  };
}
